version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/api-laravel
      - ./docker/nginx/php.ini:/usr/local/etc/php/php.ini
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "8081:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/api-laravel
    restart: always
    container_name: ${PROJECT_NAME}-php-fpm
    depends_on:
      - mysql

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./app:/api-laravel
    command: sleep 10000
    container_name: ${PROJECT_NAME}-php-cli

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    container_name: ${PROJECT_NAME}-mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - VIRTUAL_HOST=phpmyadmin.local
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8082:80

volumes:
  mysql:
